server:
  port: 8080
  tomcat:
    uri-encoding: utf-8
    max-swallow-size: -1
spring:

  banner:
    location: classpath:banner/banner.txt
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB
#  profiles:
#    active:  switch between different environment like production,test and dev

logging:
  level:
    root: info #info in production environment, debug in dev environment